[tool.poetry]
name = "kahvi"
version = "0.1.0"
description = ""
authors = ["Karri Lumivirta <lumivirta.karri@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
