name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Set environment variables for testing
        run: echo "TEST_ENV=true" >> $GITHUB_ENV
      - name: Run tests
        env:
          TEST_ENV: "true"
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: poetry run coverage run --branch -m pytest
      - name: Lint
        run: poetry run pylint src
      - name: Run Robot Framework tests
        env:
          TEST_ENV: "true"
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: robot src/tests/
        